export const HISTORY_REQUEST = "HISTORY_REQUEST";
export const HISTORY_SUCCESS = "HISTORY_SUCCESS";
export const HISTORY_FAILURE = "HISTORY_FAILURE";

export const VISITS_REQUEST = "VISITS_REQUEST";
export const VISITS_SUCCESS = "VISITS_SUCCESS";
export const VISITS_FAILURE = "VISITS_FAILURE";

export const BOOKMARKS_REQUEST = "BOOKMARKS_REQUEST";
export const BOOKMARKS_SUCCESS = "BOOKMARKS_SUCCESS";
export const BOOKMARKS_FAILURE = "BOOKMARKS_FAILURE";
